# Generated by Django 5.2 on 2025-04-28 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='mode_id',
            new_name='task_mode',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='file',
            name='file_path',
        ),
        migrations.AddField(
            model_name='file',
            name='file',
            field=models.CharField(default='default_value', max_length=255),
        ),
        migrations.AddField(
            model_name='task',
            name='task_update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_description',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='project_role',
            field=models.CharField(blank=True, choices=[('Администратор', 'Администратор'), ('Участник', 'Участник'), ('Наблюдатель', 'Наблюдатель')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='date_of_remind',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_description',
            field=models.TextField(blank=True, default='No description'),
            preserve_default=False,
        ),
    ]
