# Generated by Django 5.2 on 2025-05-08 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0003_alter_project_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskmaker_user',
            old_name='user_password',
            new_name='password',
        ),
        migrations.AddField(
            model_name='taskmaker_user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterUniqueTogether(
            name='projectmember',
            unique_together={('project', 'user')},
        ),
    ]
