# Generated by Django 5.2 on 2025-05-08 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0004_rename_user_password_taskmaker_user_password_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['task_make_date']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='task_implementer',
            new_name='assignee',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='creator',
        ),
    ]
