# Generated by Django 5.2 on 2025-05-08 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0006_task_task_implementer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskMakerUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_login', models.CharField(max_length=255, unique=True)),
                ('user_surname', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.taskmakeruser'),
        ),
        migrations.AlterField(
            model_name='projectmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskapp.taskmakeruser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='assignee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='taskapp.taskmakeruser'),
        ),
        migrations.AlterField(
            model_name='task',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_tasks', to='taskapp.taskmakeruser'),
        ),
        migrations.DeleteModel(
            name='TaskMaker_User',
        ),
    ]
