# Generated by Django 5.1.7 on 2025-05-15 21:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0009_taskmakeruser_groups_taskmakeruser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(related_name='projects', through='taskapp.ProjectMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
