# Generated by Django 5.1.7 on 2025-05-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskapp', '0010_project_members'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmember',
            options={'verbose_name': 'Project Member', 'verbose_name_plural': 'Project Members'},
        ),
    ]
